name: prompts.ir
title: prompts.ir
subtitle: کتابخانه‌ی دستورات هوش مصنوعی

repository: MohammadKani/prompts.ir

github_pages:
  url: "https://prompts.ir"
  branch: "main"

exclude:
  - assets/css/style.scss